artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  train_file: train.csv
  test_file: test.csv

data_preprocessing:
  root_dir: artifacts/data_preprocessing
  local_file: data_preprocess.csv

training:
  root_dir: artifacts/training
  local_model_file: model.pkl
  score_save: score.json